# Generated by Django 3.2.9 on 2021-12-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='img',
            field=models.ImageField(upload_to='pics2'),
        ),
    ]
