# Generated by Django 3.2.9 on 2021-12-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_auto_20211211_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='names',
            field=models.CharField(max_length=255),
        ),
    ]
